### ISSUE TITLE
Template the full image path

### ISSUE THREAD

**Issue by BrendanxP** [luixal/lovelace-media-source-image-card#13]
I want to address a minor issue I came across.
When I template only part of the image path, the card works as expected. Example:
```
type: custom:media-source-image-card
image: media-source://{{ states('sensor.image_path') }}
```
where sensor.image_path = "media_source/local/test.png"

However, when I try to template the full path the card does not work. Example
```
type: custom:media-source-image-card
image: {{ states('sensor.image_full_path') }}
```
where sensor.image_full_path = "media-source://media_source/local/test.png"

In theory, they both get the same path, but the editor gives me an error right away before I can save the card.  This is definitely not a major issue as you can just format the input as the first example. But I figured I would share it. I am on the latest version of the card.

**Comment by luixal** [comment]
Hi,

I think you have a syntax error in the second config, you have to quote the template if you're using it just like that. Indeed, when you try to edit the card after setting it that way, you should see some object related weird config.

You can just quote the template like this:

```yaml
type: custom:media-source-image-card
image: "{{ states('sensor.image_full_path') }}"
```

or you can set the template as in other cards:

```yaml
type: custom:media-source-image-card
image: |
  {{ states('sensor.image_full_path') }}
```

Why does the first case works? I guess HA is casting the template to string instead of thinking you're providing and object.

Give it a try :)

**Comment by BrendanxP** [comment]
You are absolutely correct! Big thanks for getting back to me again so quickly and pointing out my mistake.
With edge cases like this, Home Assistant templating is not always very straightforward...
